# Permalinks
permalink:           pretty


# Setup
title:               CUFE
tagline:             '中央财经大学MBA学习资源'
description:         ''
baseurl:            https://cufembaer.github.io
paginate:            5

# About/contact
author:
  name:              J.Jiang
  url:               https://jiangzerui.cn
  email:             stonefavorite@126.com

# Custom vars
version:             1.0.0
